name: tebac_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.1.0
  cupertino_icons: ^1.0.8

  image_picker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1  

flutter_icons:  
  android: true
  ios: true
  image_path: "images/logo1.jpeg"

flutter:
  uses-material-design: true
  assets:
    - images/coart1.jpeg
    - images/coart2.jpeg
    - images/coart4.jpeg
    - images/logo1.jpeg
    - images/icon1.jpeg
